[package]
name = "feval"
version = "0.1.1"
edition = "2021"
description = "clt for fast evaluations"
readme = "README.md"
repository = "https://github.com/ivabus/feval"
license = "MIT"
authors = ["Ivan ivabus Bushchik"]

[dependencies]
evalexpr = "8.1.0"
